###################
# DEPLOYMENT
###################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-ia-test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # No dejar pods no disponibles durante la actualización
  selector:
    matchLabels:
      app: springboot-ia-test
  template:
    metadata:
      labels:
        app: springboot-ia-test
    spec:
      containers:
      - name: springboot-ia-test
        image: federicomartinlara1976/springboot-ia-test:1.0.10  # Cambia esta etiqueta
        imagePullPolicy: Always  # Siempre extraer la imagen más reciente
        ports:
        - containerPort: 8084
---	
###################
# SERVICIO
###################
apiVersion: v1
kind: Service
metadata:
  name: springboot-ia-test-svc
  labels:
    app: springboot-ia-test
spec:
  type: NodePort
  selector:
    app: springboot-ia-test
  ports:
    - port: 8084
      nodePort: 8084    
      protocol: TCP
